# Generated by Django 4.1.6 on 2023-12-03 04:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ClassWise', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_duration',
            new_name='course_instructors',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_fee',
            new_name='course_offering_terms',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_date_created',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_image',
        ),
        migrations.AddField(
            model_name='course',
            name='course_credit',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='course_prerequisites',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='course_previous_grade',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
