# Generated by Django 4.1 on 2023-12-06 07:26

from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor_name', models.CharField(max_length=200)),
                ('instructor_rating', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('course_code', models.CharField(max_length=200)),
                ('course_description', models.CharField(max_length=200)),
                ('course_restrictions', models.CharField(max_length=1000, null=True)),
                ('course_offering_terms', models.CharField(max_length=200, null=True)),
                ('course_previous_grades', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), null=True, size=None)),
                ('course_credit', models.PositiveIntegerField()),
                ('course_corequisites', models.ManyToManyField(related_name='corequisite_of', to='ClassWise.course')),
                ('course_instructors', models.ManyToManyField(to='ClassWise.instructor')),
                ('course_prerequisites', models.ManyToManyField(related_name='prerequisite_of', to='ClassWise.course')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=200, null=True)),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('comment_course', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ClassWise.course')),
                ('comment_professor', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='ClassWise.instructor')),
                ('comment_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
