# Generated by Django 4.1.6 on 2023-12-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200, null=True)),
                ('course_code', models.CharField(max_length=200, null=True)),
                ('course_duration', models.CharField(max_length=200, null=True)),
                ('course_fee', models.CharField(max_length=200, null=True)),
                ('course_description', models.CharField(max_length=200, null=True)),
                ('course_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('course_date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
