# Generated by Django 4.1 on 2023-12-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassWise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_previous_grades',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
