# Generated by Django 4.1.6 on 2023-12-03 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClassWise', '0002_rename_course_duration_course_course_instructors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_credit',
        ),
    ]
