# Generated by Django 4.1 on 2023-12-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassWise', '0002_rename_comment_professor_comment_comment_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_instructor',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
