# Generated by Django 4.1 on 2023-12-09 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassWise', '0002_alter_course_course_previous_grades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_previous_grades',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_restrictions',
            field=models.TextField(null=True),
        ),
    ]
