# Generated by Django 4.1 on 2023-12-11 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassWise', '0002_instructor_level_of_difficulty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='link',
            field=models.URLField(null=True),
        ),
    ]
