# Generated by Django 4.1 on 2023-12-11 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassWise', '0003_instructor_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='level_of_difficulty',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
