# Generated by Django 4.1 on 2023-12-09 06:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassWise', '0003_alter_course_course_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_previous_grades',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='instructor_rating',
            field=models.FloatField(default=0.0, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
