# Generated by Django 4.2.7 on 2023-12-11 11:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassWise', '0003_alter_comment_comment_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_grade',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_rating',
            field=models.SmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
