# Generated by Django 4.2.7 on 2023-12-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassWise', '0004_comment_comment_grade_comment_comment_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_corequisites',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_prerequisites',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
