# Generated by Django 4.1 on 2023-12-10 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassWise', '0004_alter_course_course_previous_grades_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_credit',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
