# Generated by Django 4.1 on 2023-12-11 00:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassWise', '0004_alter_instructor_level_of_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='level_of_difficulty',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='would_take_again',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
