# Generated by Django 4.1 on 2023-12-11 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassWise', '0005_alter_instructor_level_of_difficulty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_corequisites',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_prerequisites',
        ),
        migrations.AddField(
            model_name='course',
            name='course_corequisites',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='course_prerequisites',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
